apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssqldata-claim
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmqdata-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
